### ISSUE TITLE
remove evil dependency

### ISSUE THREAD

**Issue by sam217pa** [chameco/raven#2]
Hi, 

I don't think that evil should be required for raven to run by default.
There's only 4 line of code that demands evil, and I think these lines
can be set up "from outside" of raven.

Thanks for raven, it looks cool !

**Comment by chameco** [comment]
The Evil dependency is intentional: it allows for tighter integration with Evil in the future without potentially "burning" any users that depended on functionality that doesn't require Evil.

If you wish to use Raven in a workflow that doesn't include Evil, that's great of course! Feel free to remove those lines locally. But for now, I intend to keep them, and if anything add *more* Evil-related code, not less.

**Comment by sam217pa** [comment]
Alright, that makes sense then 👍

**Comment by tsdh** [comment]
@chameco Does your statement still stand given that you haven't been added any more evil calls for almost one year?

In https://github.com/tsdh/raven/tree/do-no-evil I made Evil optional (i.e., if it is already installed, it'll be equivalent to your master branch), but if not, it won't be required.  I would submit a PR in case your plans have changed.

**Comment by chameco** [comment]
@tsdh It's funny how things work out sometimes. Before I started using Raven in earnest, I thought I would likely be dissatisfied with the UI and have to make regular changes. That hasn't happened.

After one year of using Raven very heavily (my tracking indicates I call `raven` around 800 times daily on average), I am happy with the interface, and it is unlikely that I will make substantial changes.

As such, removing the Evil dependency seems fine to me. Feel free to send over a pull request!

**Comment by tsdh** [comment]
:+1:
